In [1]:
import numpy as np
import pandas as pd
import json
from pandas import json_normalize
import requests
import re
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from bs4 import BeautifulSoup

In [2]:
URL = "https://www.flipkart.com/search?q=drones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off=1"
page = requests.get(URL)
page

In [3]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time

productname = []
price = []
rating = []
features = []
pagenum = []
original_price = []
Discount = []
Review = []

total_time = time.time()


for i in range(1,539):
    start_time = time.time()
    URL = f"https://www.flipkart.com/search?q=drones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off={i}"
    page = requests.get(URL)
    soup = BeautifulSoup(page.text, "html.parser")

    for x in soup.find_all('div', attrs={'class':'ZFwe0M row'}):
        pname = x.find('div', attrs={'class':'RG5Slk'})
        cost = x.find('div', attrs={'class':'hZ3P6w DeU9vF'})   # discounted price
        rat = x.find('div', attrs={'class':'MKiFS6'})
        specs = x.find('div', attrs={'class':'CMXw7N'})
        op = x.find('div', attrs={'class':'kRYCnD gxR4EY'})
        discount = x.find('div', attrs={'class':'HQe8jr'})
        reviews = x.find('span', attrs={'class':'PvbNMB'})


        productname.append(pname.text if pname else np.nan)
        price.append(cost.text if cost else np.nan)
        rating.append(rat.text if rat else np.nan)
        features.append(specs.text if specs else np.nan)
        original_price.append(op.text if op else np.nan)
        Discount.append(discount.text if discount else np.nan)
        Review.append(reviews.text if reviews else np.nan)

        pagenum.append(i)

    print(f'Page {i} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 3.78 seconds
Page 2 completed in 1.67 seconds
Page 3 completed in 1.74 seconds
Page 4 completed in 0.74 seconds
Page 5 completed in 1.45 seconds
Page 6 completed in 4.29 seconds
Page 7 completed in 3.10 seconds
Page 8 completed in 7.98 seconds
Page 9 completed in 7.83 seconds
Page 10 completed in 2.23 seconds
Page 11 completed in 2.35 seconds
Page 12 completed in 0.25 seconds
Page 13 completed in 1.18 seconds
Page 14 completed in 2.02 seconds
Page 15 completed in 6.02 seconds
Page 16 completed in 3.37 seconds
Page 17 completed in 0.28 seconds
Page 18 completed in 0.89 seconds
Page 19 completed in 1.08 seconds
Page 20 completed in 1.03 seconds
Page 21 completed in 0.42 seconds
Page 22 completed in 1.19 seconds
Page 23 completed in 1.50 seconds
Page 24 completed in 1.61 seconds
Page 25 completed in 2.03 seconds
Page 26 completed in 6.11 seconds
Page 27 completed in 3.59 seconds
Page 28 completed in 2.23 seconds
Page 29 completed in 1.52 seconds
Page 30 completed in 10.53 seconds
Page 31 completed in 6.13 seconds
Page 32 completed in 3.53 seconds
Page 33 completed in 3.64 seconds
Page 34 completed in 2.69 seconds
Page 35 completed in 1.98 seconds
Page 36 completed in 2.80 seconds
Page 37 completed in 5.32 seconds
Page 38 completed in 4.90 seconds
Page 39 completed in 18.42 seconds
Page 40 completed in 4.32 seconds
Page 41 completed in 1.40 seconds
Page 42 completed in 0.82 seconds
Page 43 completed in 1.48 seconds
Page 44 completed in 1.08 seconds
Page 45 completed in 1.06 seconds
Page 46 completed in 1.04 seconds
Page 47 completed in 0.63 seconds
Page 48 completed in 1.09 seconds
Page 49 completed in 1.11 seconds
Page 50 completed in 0.88 seconds
Page 51 completed in 1.14 seconds
Page 52 completed in 0.44 seconds
Page 53 completed in 1.00 seconds
Page 54 completed in 1.26 seconds
Page 55 completed in 0.87 seconds
Page 56 completed in 1.28 seconds
Page 57 completed in 1.03 seconds
Page 58 completed in 1.18 seconds
Page 59 completed in 1.86 seconds
Page 60 completed in 1.69 seconds
Page 61 completed in 1.30 seconds
Page 62 completed in 1.12 seconds
Page 63 completed in 1.27 seconds
Page 64 completed in 2.48 seconds
Page 65 completed in 1.54 seconds
Page 66 completed in 1.12 seconds
Page 67 completed in 6.26 seconds
Page 68 completed in 1.52 seconds
Page 69 completed in 0.98 seconds
Page 70 completed in 0.89 seconds
Page 71 completed in 1.27 seconds
Page 72 completed in 1.29 seconds
Page 73 completed in 1.18 seconds
Page 74 completed in 1.66 seconds
Page 75 completed in 1.40 seconds
Page 76 completed in 0.79 seconds
Page 77 completed in 0.85 seconds
Page 78 completed in 0.77 seconds
Page 79 completed in 1.02 seconds
Page 80 completed in 1.49 seconds
Page 81 completed in 0.69 seconds
Page 82 completed in 0.92 seconds
Page 83 completed in 0.99 seconds
Page 84 completed in 1.33 seconds
Page 85 completed in 0.83 seconds
Page 86 completed in 1.15 seconds
Page 87 completed in 1.30 seconds
Page 88 completed in 0.68 seconds
Page 89 completed in 0.70 seconds
Page 90 completed in 0.86 seconds
Page 91 completed in 0.87 seconds
Page 92 completed in 0.63 seconds
Page 93 completed in 0.98 seconds
Page 94 completed in 0.78 seconds
Page 95 completed in 1.88 seconds
Page 96 completed in 0.97 seconds
Page 97 completed in 0.91 seconds
Page 98 completed in 0.94 seconds
Page 99 completed in 0.92 seconds
Page 100 completed in 1.22 seconds
Page 101 completed in 1.37 seconds
Page 102 completed in 2.61 seconds
Page 103 completed in 1.88 seconds
Page 104 completed in 1.62 seconds
Page 105 completed in 1.08 seconds
Page 106 completed in 0.95 seconds
Page 107 completed in 1.31 seconds
Page 108 completed in 1.16 seconds
Page 109 completed in 1.30 seconds
Page 110 completed in 1.53 seconds
Page 111 completed in 6.27 seconds
Page 112 completed in 9.52 seconds
Page 113 completed in 2.39 seconds
Page 114 completed in 1.56 seconds
Page 115 completed in 1.37 seconds
Page 116 completed in 0.91 seconds
Page 117 completed in 0.98 seconds
Page 118 completed in 1.24 seconds
Page 119 completed in 1.36 seconds
Page 120 completed in 1.62 seconds
Page 121 completed in 1.14 seconds
Page 122 completed in 0.94 seconds
Page 123 completed in 1.73 seconds
Page 124 completed in 7.67 seconds
Page 125 completed in 4.45 seconds
Page 126 completed in 4.15 seconds
Page 127 completed in 3.29 seconds
Page 128 completed in 1.19 seconds
Page 129 completed in 1.78 seconds
Page 130 completed in 1.91 seconds
Page 131 completed in 1.17 seconds
Page 132 completed in 1.60 seconds
Page 133 completed in 1.14 seconds
Page 134 completed in 0.92 seconds
Page 135 completed in 1.14 seconds
Page 136 completed in 1.09 seconds
Page 137 completed in 1.25 seconds
Page 138 completed in 0.84 seconds
Page 139 completed in 1.01 seconds
Page 140 completed in 0.95 seconds
Page 141 completed in 0.93 seconds
Page 142 completed in 0.96 seconds
Page 143 completed in 1.09 seconds
Page 144 completed in 0.84 seconds
Page 145 completed in 0.83 seconds
Page 146 completed in 1.33 seconds
Page 147 completed in 0.84 seconds
Page 148 completed in 0.84 seconds
Page 149 completed in 0.67 seconds
Page 150 completed in 0.70 seconds
Page 151 completed in 0.87 seconds
Page 152 completed in 0.79 seconds
Page 153 completed in 1.24 seconds
Page 154 completed in 0.97 seconds
Page 155 completed in 1.38 seconds
Page 156 completed in 1.09 seconds
Page 157 completed in 1.11 seconds
Page 158 completed in 1.36 seconds
Page 159 completed in 0.65 seconds
Page 160 completed in 0.70 seconds
Page 161 completed in 0.80 seconds
Page 162 completed in 1.18 seconds
Page 163 completed in 0.90 seconds
Page 164 completed in 0.88 seconds
Page 165 completed in 0.66 seconds
Page 166 completed in 0.60 seconds
Page 167 completed in 0.98 seconds
Page 168 completed in 1.37 seconds
Page 169 completed in 1.17 seconds
Page 170 completed in 2.23 seconds
Page 171 completed in 1.04 seconds
Page 172 completed in 1.24 seconds
Page 173 completed in 0.80 seconds
Page 174 completed in 0.79 seconds
Page 175 completed in 0.62 seconds
Page 176 completed in 0.65 seconds
Page 177 completed in 0.64 seconds
Page 178 completed in 0.89 seconds
Page 179 completed in 1.42 seconds
Page 180 completed in 0.92 seconds
Page 181 completed in 0.72 seconds
Page 182 completed in 0.80 seconds
Page 183 completed in 0.92 seconds
Page 184 completed in 0.79 seconds
Page 185 completed in 1.09 seconds
Page 186 completed in 1.07 seconds
Page 187 completed in 1.12 seconds
Page 188 completed in 1.52 seconds
Page 189 completed in 0.75 seconds
Page 190 completed in 0.79 seconds
Page 191 completed in 1.31 seconds
Page 192 completed in 0.60 seconds
Page 193 completed in 1.30 seconds
Page 194 completed in 1.36 seconds
Page 195 completed in 1.71 seconds
Page 196 completed in 1.47 seconds
Page 197 completed in 1.56 seconds
Page 198 completed in 0.54 seconds
Page 199 completed in 0.73 seconds
Page 200 completed in 0.85 seconds
Page 201 completed in 0.78 seconds
Page 202 completed in 0.53 seconds
Page 203 completed in 0.62 seconds
Page 204 completed in 0.65 seconds
Page 205 completed in 1.02 seconds
Page 206 completed in 0.84 seconds
Page 207 completed in 0.74 seconds
Page 208 completed in 1.22 seconds
Page 209 completed in 0.86 seconds
Page 210 completed in 1.09 seconds
Page 211 completed in 0.72 seconds
Page 212 completed in 0.52 seconds
Page 213 completed in 0.88 seconds
Page 214 completed in 1.03 seconds
Page 215 completed in 0.70 seconds
Page 216 completed in 0.75 seconds
Page 217 completed in 0.55 seconds
Page 218 completed in 0.79 seconds
Page 219 completed in 1.08 seconds
Page 220 completed in 0.84 seconds
Page 221 completed in 0.96 seconds
Page 222 completed in 0.58 seconds
Page 223 completed in 0.75 seconds
Page 224 completed in 0.93 seconds
Page 225 completed in 0.50 seconds
Page 226 completed in 0.67 seconds
Page 227 completed in 0.70 seconds
Page 228 completed in 0.52 seconds
Page 229 completed in 0.85 seconds
Page 230 completed in 0.85 seconds
Page 231 completed in 0.70 seconds
Page 232 completed in 0.57 seconds
Page 233 completed in 0.95 seconds
Page 234 completed in 0.52 seconds
Page 235 completed in 0.60 seconds
Page 236 completed in 0.71 seconds
Page 237 completed in 0.62 seconds
Page 238 completed in 0.71 seconds
Page 239 completed in 0.65 seconds
Page 240 completed in 1.42 seconds
Page 241 completed in 1.30 seconds
Page 242 completed in 0.90 seconds
Page 243 completed in 0.58 seconds
Page 244 completed in 0.61 seconds
Page 245 completed in 1.01 seconds
Page 246 completed in 0.79 seconds
Page 247 completed in 1.52 seconds
Page 248 completed in 1.26 seconds
Page 249 completed in 1.69 seconds
Page 250 completed in 2.15 seconds
Page 251 completed in 1.33 seconds
Page 252 completed in 3.77 seconds
Page 253 completed in 1.78 seconds
Page 254 completed in 0.99 seconds
Page 255 completed in 1.45 seconds
Page 256 completed in 3.54 seconds
Page 257 completed in 1.26 seconds
Page 258 completed in 1.11 seconds
Page 259 completed in 1.45 seconds
Page 260 completed in 2.90 seconds
Page 261 completed in 1.24 seconds
Page 262 completed in 1.67 seconds
Page 263 completed in 1.04 seconds
Page 264 completed in 1.54 seconds
Page 265 completed in 1.23 seconds
Page 266 completed in 0.70 seconds
Page 267 completed in 1.91 seconds
Page 268 completed in 1.43 seconds
Page 269 completed in 4.11 seconds
Page 270 completed in 5.34 seconds
Page 271 completed in 4.46 seconds
Page 272 completed in 2.91 seconds
Page 273 completed in 1.14 seconds
Page 274 completed in 2.37 seconds
Page 275 completed in 1.86 seconds
Page 276 completed in 3.36 seconds
Page 277 completed in 1.60 seconds
Page 278 completed in 2.16 seconds
Page 279 completed in 7.16 seconds
Page 280 completed in 2.27 seconds
Page 281 completed in 1.88 seconds
Page 282 completed in 1.97 seconds
Page 283 completed in 0.84 seconds
Page 284 completed in 3.09 seconds
Page 285 completed in 4.71 seconds
Page 286 completed in 0.82 seconds
Page 287 completed in 0.89 seconds
Page 288 completed in 1.35 seconds
Page 289 completed in 4.18 seconds
Page 290 completed in 1.86 seconds
Page 291 completed in 1.19 seconds
Page 292 completed in 0.97 seconds
Page 293 completed in 1.51 seconds
Page 294 completed in 6.01 seconds
Page 295 completed in 1.24 seconds
Page 296 completed in 2.18 seconds
Page 297 completed in 2.00 seconds
Page 298 completed in 1.23 seconds
Page 299 completed in 0.86 seconds
Page 300 completed in 1.32 seconds
Page 301 completed in 1.93 seconds
Page 302 completed in 4.37 seconds
Page 303 completed in 1.68 seconds
Page 304 completed in 2.36 seconds
Page 305 completed in 1.21 seconds
Page 306 completed in 1.48 seconds
Page 307 completed in 2.40 seconds
Page 308 completed in 2.25 seconds
Page 309 completed in 1.19 seconds
Page 310 completed in 1.14 seconds
Page 311 completed in 0.68 seconds
Page 312 completed in 0.99 seconds
Page 313 completed in 0.63 seconds
Page 314 completed in 0.75 seconds
Page 315 completed in 0.92 seconds
Page 316 completed in 2.32 seconds
Page 317 completed in 1.01 seconds
Page 318 completed in 0.94 seconds
Page 319 completed in 1.47 seconds
Page 320 completed in 0.80 seconds
Page 321 completed in 0.86 seconds
Page 322 completed in 5.35 seconds
Page 323 completed in 1.41 seconds
Page 324 completed in 1.45 seconds
Page 325 completed in 2.72 seconds
Page 326 completed in 0.95 seconds
Page 327 completed in 0.56 seconds
Page 328 completed in 1.47 seconds
Page 329 completed in 0.23 seconds
Page 330 completed in 0.88 seconds
Page 331 completed in 1.35 seconds
Page 332 completed in 0.75 seconds
Page 333 completed in 1.09 seconds
Page 334 completed in 1.44 seconds
Page 335 completed in 2.97 seconds
Page 336 completed in 1.77 seconds
Page 337 completed in 2.45 seconds
Page 338 completed in 0.72 seconds
Page 339 completed in 0.94 seconds
Page 340 completed in 0.87 seconds
Page 341 completed in 3.31 seconds
Page 342 completed in 1.38 seconds
Page 343 completed in 1.97 seconds
Page 344 completed in 1.20 seconds
Page 345 completed in 0.76 seconds
Page 346 completed in 1.08 seconds
Page 347 completed in 1.98 seconds
Page 348 completed in 1.89 seconds
Page 349 completed in 1.12 seconds
Page 350 completed in 1.30 seconds
Page 351 completed in 1.67 seconds
Page 352 completed in 1.55 seconds
Page 353 completed in 1.51 seconds
Page 354 completed in 2.43 seconds
Page 355 completed in 0.91 seconds
Page 356 completed in 0.78 seconds
Page 357 completed in 0.93 seconds
Page 358 completed in 1.79 seconds
Page 359 completed in 1.66 seconds
Page 360 completed in 0.73 seconds
Page 361 completed in 1.70 seconds
Page 362 completed in 1.26 seconds
Page 363 completed in 1.38 seconds
Page 364 completed in 1.50 seconds
Page 365 completed in 0.89 seconds
Page 366 completed in 0.98 seconds
Page 367 completed in 2.00 seconds
Page 368 completed in 0.93 seconds
Page 369 completed in 1.17 seconds
Page 370 completed in 0.74 seconds
Page 371 completed in 1.36 seconds
Page 372 completed in 0.84 seconds
Page 373 completed in 1.08 seconds
Page 374 completed in 2.08 seconds
Page 375 completed in 0.79 seconds
Page 376 completed in 1.41 seconds
Page 377 completed in 1.10 seconds
Page 378 completed in 0.63 seconds
Page 379 completed in 0.69 seconds
Page 380 completed in 0.70 seconds
Page 381 completed in 0.88 seconds
Page 382 completed in 1.06 seconds
Page 383 completed in 0.69 seconds
Page 384 completed in 1.75 seconds
Page 385 completed in 0.69 seconds
Page 386 completed in 0.54 seconds
Page 387 completed in 0.60 seconds
Page 388 completed in 0.84 seconds
Page 389 completed in 0.57 seconds
Page 390 completed in 0.62 seconds
Page 391 completed in 0.69 seconds
Page 392 completed in 0.06 seconds
Page 393 completed in 0.69 seconds
Page 394 completed in 0.12 seconds
Page 395 completed in 0.57 seconds
Page 396 completed in 0.58 seconds
Page 397 completed in 0.68 seconds
Page 398 completed in 0.60 seconds
Page 399 completed in 0.27 seconds
Page 400 completed in 1.36 seconds
Page 401 completed in 1.34 seconds
Page 402 completed in 0.26 seconds
Page 403 completed in 0.09 seconds
Page 404 completed in 0.70 seconds
Page 405 completed in 0.06 seconds
Page 406 completed in 0.58 seconds
Page 407 completed in 0.64 seconds
Page 408 completed in 0.71 seconds
Page 409 completed in 2.88 seconds
Page 410 completed in 0.92 seconds
Page 411 completed in 0.13 seconds
Page 412 completed in 0.65 seconds
Page 413 completed in 1.50 seconds
Page 414 completed in 1.50 seconds
Page 415 completed in 0.91 seconds
Page 416 completed in 0.96 seconds
Page 417 completed in 0.19 seconds
Page 418 completed in 0.67 seconds
Page 419 completed in 0.53 seconds
Page 420 completed in 0.61 seconds
Page 421 completed in 0.72 seconds
Page 422 completed in 0.91 seconds
Page 423 completed in 0.58 seconds
Page 424 completed in 0.76 seconds
Page 425 completed in 0.52 seconds
Page 426 completed in 0.50 seconds
Page 427 completed in 0.54 seconds
Page 428 completed in 0.69 seconds
Page 429 completed in 0.67 seconds
Page 430 completed in 0.64 seconds
Page 431 completed in 0.59 seconds
Page 432 completed in 0.53 seconds
Page 433 completed in 0.70 seconds
Page 434 completed in 0.54 seconds
Page 435 completed in 0.54 seconds
Page 436 completed in 0.63 seconds
Page 437 completed in 0.74 seconds
Page 438 completed in 1.60 seconds
Page 439 completed in 0.45 seconds
Page 440 completed in 0.51 seconds
Page 441 completed in 0.59 seconds
Page 442 completed in 0.62 seconds
Page 443 completed in 0.52 seconds
Page 444 completed in 0.46 seconds
Page 445 completed in 0.96 seconds
Page 446 completed in 0.54 seconds
Page 447 completed in 0.50 seconds
Page 448 completed in 0.92 seconds
Page 449 completed in 0.48 seconds
Page 450 completed in 0.49 seconds
Page 451 completed in 0.50 seconds
Page 452 completed in 0.55 seconds
Page 453 completed in 0.72 seconds
Page 454 completed in 0.67 seconds
Page 455 completed in 0.99 seconds
Page 456 completed in 0.74 seconds
Page 457 completed in 0.66 seconds
Page 458 completed in 0.76 seconds
Page 459 completed in 0.65 seconds
Page 460 completed in 0.63 seconds
Page 461 completed in 0.61 seconds
Page 462 completed in 0.64 seconds
Page 463 completed in 0.93 seconds
Page 464 completed in 0.90 seconds
Page 465 completed in 0.65 seconds
Page 466 completed in 0.97 seconds
Page 467 completed in 0.87 seconds
Page 468 completed in 0.63 seconds
Page 469 completed in 0.61 seconds
Page 470 completed in 0.67 seconds
Page 471 completed in 0.53 seconds
Page 472 completed in 1.03 seconds
Page 473 completed in 0.85 seconds
Page 474 completed in 0.80 seconds
Page 475 completed in 0.55 seconds
Page 476 completed in 0.57 seconds
Page 477 completed in 0.60 seconds
Page 478 completed in 0.52 seconds
Page 479 completed in 0.49 seconds
Page 480 completed in 0.55 seconds
Page 481 completed in 0.47 seconds
Page 482 completed in 0.42 seconds
Page 483 completed in 0.49 seconds
Page 484 completed in 0.50 seconds
Page 485 completed in 0.52 seconds
Page 486 completed in 0.52 seconds
Page 487 completed in 0.84 seconds
Page 488 completed in 0.62 seconds
Page 489 completed in 0.63 seconds
Page 490 completed in 0.48 seconds
Page 491 completed in 0.46 seconds
Page 492 completed in 0.56 seconds
Page 493 completed in 0.64 seconds
Page 494 completed in 0.73 seconds
Page 495 completed in 0.54 seconds
Page 496 completed in 0.55 seconds
Page 497 completed in 0.75 seconds
Page 498 completed in 0.56 seconds
Page 499 completed in 0.69 seconds
Page 500 completed in 0.97 seconds
Page 501 completed in 0.68 seconds
Page 502 completed in 0.54 seconds
Page 503 completed in 0.70 seconds
Page 504 completed in 0.53 seconds
Page 505 completed in 0.72 seconds
Page 506 completed in 0.68 seconds
Page 507 completed in 0.73 seconds
Page 508 completed in 1.01 seconds
Page 509 completed in 0.54 seconds
Page 510 completed in 0.94 seconds
Page 511 completed in 0.51 seconds
Page 512 completed in 1.14 seconds
Page 513 completed in 0.58 seconds
Page 514 completed in 0.66 seconds
Page 515 completed in 0.57 seconds
Page 516 completed in 1.27 seconds
Page 517 completed in 2.76 seconds
Page 518 completed in 1.38 seconds
Page 519 completed in 1.47 seconds
Page 520 completed in 1.31 seconds
Page 521 completed in 0.08 seconds
Page 522 completed in 0.12 seconds
Page 523 completed in 0.60 seconds
Page 524 completed in 0.60 seconds
Page 525 completed in 0.72 seconds
Page 526 completed in 0.70 seconds
Page 527 completed in 0.59 seconds
Page 528 completed in 0.64 seconds
Page 529 completed in 1.34 seconds
Page 530 completed in 0.89 seconds
Page 531 completed in 0.57 seconds
Page 532 completed in 0.73 seconds
Page 533 completed in 1.07 seconds
Page 534 completed in 0.97 seconds
Page 535 completed in 0.63 seconds
Page 536 completed in 1.85 seconds
Page 537 completed in 1.09 seconds
Page 538 completed in 0.77 seconds
Total Time Completed in seconds 731.9452819824219

In [4]:
df = pd.DataFrame({"product_name":productname,"price":price,"Rating":rating,"Features":features,"pagenum":pagenum,"original_price":original_price,"Discount":Discount,"Review":Review})

In [5]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",NaN,Type: Mini DroneControl Range: 100 ftBattery T...,1,"₹5,999",52% off,NaN
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,"₹3,248",3.2,Type: Professional DroneControl Range: 200 ftB...,1,"₹12,999",75% off,487 Ratings & 24 Reviews
2,harshiv E88 Pro Drone 4k HD foldable With Came...,"₹1,749",1.8,Type: Mini DroneControl Range: 60 ftPower Cons...,1,"₹4,999",65% off,6 Ratings & 1 Reviews
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...","₹1,649",3.2,Type: Mini DroneControl Range: 100 mPower Cons...,1,"₹2,899",43% off,83 Ratings & 4 Reviews
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,"₹2,599",2.8,Type: Mini DroneControl Range: 100 ftBattery T...,1,"₹6,999",62% off,62 Ratings & 2 Reviews
...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,"₹3,780",NaN,Type: Professional DroneControl Range: 200 mPo...,538,"₹7,999",52% off,NaN
12452,TodFod E88 with double Battery Drone,"₹1,910",NaN,Type: Mini DroneControl Range: 50 ftBattery Ty...,538,"₹3,999",52% off,NaN
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,"₹7,455",3.1,Type: Professional DroneControl Range: 500 mPo...,538,"₹14,999",50% off,30 Ratings & 0 Reviews
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,"₹7,644",1,Type: Professional DroneControl Range: 98 ftPo...,538,"₹9,990",23% off,2 Ratings & 1 Reviews
12455,Fourbrother Black Quadcopter Drone,"₹1,971",3.2,Type: Professional DroneControl Range: 100 mBa...,538,"₹19,999",90% off,318 Ratings & 9 Reviews

In [6]:
df.to_csv("flipkart_drones_new.csv",index = False)

In [7]:
df = pd.read_csv("flipkart_drones_new.csv")

In [8]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",NaN,Type: Mini DroneControl Range: 100 ftBattery T...,1,"₹5,999",52% off,NaN
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,"₹3,248",3.2,Type: Professional DroneControl Range: 200 ftB...,1,"₹12,999",75% off,487 Ratings & 24 Reviews
2,harshiv E88 Pro Drone 4k HD foldable With Came...,"₹1,749",1.8,Type: Mini DroneControl Range: 60 ftPower Cons...,1,"₹4,999",65% off,6 Ratings & 1 Reviews
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...","₹1,649",3.2,Type: Mini DroneControl Range: 100 mPower Cons...,1,"₹2,899",43% off,83 Ratings & 4 Reviews
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,"₹2,599",2.8,Type: Mini DroneControl Range: 100 ftBattery T...,1,"₹6,999",62% off,62 Ratings & 2 Reviews
...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,"₹3,780",NaN,Type: Professional DroneControl Range: 200 mPo...,538,"₹7,999",52% off,NaN
12452,TodFod E88 with double Battery Drone,"₹1,910",NaN,Type: Mini DroneControl Range: 50 ftBattery Ty...,538,"₹3,999",52% off,NaN
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,"₹7,455",3.1,Type: Professional DroneControl Range: 500 mPo...,538,"₹14,999",50% off,30 Ratings & 0 Reviews
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,"₹7,644",1.0,Type: Professional DroneControl Range: 98 ftPo...,538,"₹9,990",23% off,2 Ratings & 1 Reviews
12455,Fourbrother Black Quadcopter Drone,"₹1,971",3.2,Type: Professional DroneControl Range: 100 mBa...,538,"₹19,999",90% off,318 Ratings & 9 Reviews

In [9]:
df.shape

(12456, 8)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12456 entries, 0 to 12455
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_name    12456 non-null  object
 1   price           12432 non-null  object
 2   Rating          9720 non-null   float64
 3   Features        12456 non-null  object
 4   pagenum         12456 non-null  int64
 5   original_price  12432 non-null  object
 6   Discount        12432 non-null  object
 7   Review          9720 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 778.6+ KB

In [11]:
#find null values.

In [12]:
df.isnull().sum()

product_name         0
price               24
Rating            2736
Features             0
pagenum              0
original_price      24
Discount            24
Review            2736
dtype: int64

In [13]:
df["Rating"].mode()[0]

np.float64(3.0)

In [14]:
df["Rating"].fillna(df["Rating"].mode()[0],inplace = True)

In [15]:
df["Review"].fillna(df["Review"].mode()[0],inplace = True)

In [16]:
df.isnull().sum()

product_name       0
price             24
Rating             0
Features           0
pagenum            0
original_price    24
Discount          24
Review             0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df["product_name"]

0        EarShades J2 Pro Foldable Drone with HD Camera...
1        Super Toy Brushless 4K Dual Camera Drone 5-Sid...
2        harshiv E88 Pro Drone 4k HD foldable With Came...
3        JOYBOX Foldable Drone with Full HD Camera, WiF...
4        NOWAIT Advanced E88 4K Dual Camera Drone with ...
                               ...
12451                                   VYZN MAX-FLY Drone
12452                 TodFod E88 with double Battery Drone
12453    GAMESOUL JS39P 4K Brushless Motor With Gimbal ...
12454    GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...
12455                   Fourbrother Black Quadcopter Drone
Name: product_name, Length: 12456, dtype: object

In [19]:
#using regular expressions

In [20]:
df["Brand"] = df["product_name"].apply(lambda x:re.findall(r"^\w+",x)[0])

In [21]:
df.head(1)

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",3.0,Type: Mini DroneControl Range: 100 ftBattery T...,1,"₹5,999",52% off,3 Ratings & 0 Reviews,EarShades

In [22]:
df["processor"] = df["Features"].apply(lambda x:re.findall(r"^\w+",x)[0])

In [23]:
df["processor"].value_counts()

processor
Type    12456
Name: count, dtype: int64

In [24]:
df["Features"] = df["Features"].str.replace(r".*Type:\s*", "", regex=True)

In [25]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",3.0,Lithium BatteryWeight: 0.3 kgNA,1,"₹5,999",52% off,3 Ratings & 0 Reviews,EarShades,Type
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,"₹3,248",3.2,Lithium BatteryWeight: 410 gno,1,"₹12,999",75% off,487 Ratings & 24 Reviews,Super,Type
2,harshiv E88 Pro Drone 4k HD foldable With Came...,"₹1,749",1.8,Lithium BatteryWeight: 200 gNA,1,"₹4,999",65% off,6 Ratings & 1 Reviews,harshiv,Type
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...","₹1,649",3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,"₹2,899",43% off,83 Ratings & 4 Reviews,JOYBOX,Type
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,"₹2,599",2.8,Lithium BatteryWeight: 0.3 kgNA,1,"₹6,999",62% off,62 Ratings & 2 Reviews,NOWAIT,Type
...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,"₹3,780",3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,"₹7,999",52% off,3 Ratings & 0 Reviews,VYZN,Type
12452,TodFod E88 with double Battery Drone,"₹1,910",3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,"₹3,999",52% off,3 Ratings & 0 Reviews,TodFod,Type
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,"₹7,455",3.1,Lithium BatteryWeight: 1.14 kgna,538,"₹14,999",50% off,30 Ratings & 0 Reviews,GAMESOUL,Type
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,"₹7,644",1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,"₹9,990",23% off,2 Ratings & 1 Reviews,GAMESOUL,Type
12455,Fourbrother Black Quadcopter Drone,"₹1,971",3.2,Lithium BatteryWeight: 320 gNA,538,"₹19,999",90% off,318 Ratings & 9 Reviews,Fourbrother,Type

In [26]:
df["processor"] = df["Features"].apply(lambda x:re.findall(r"^\w+",x)[0])

In [27]:
df["processor"].value_counts()

processor
Lithium    10889
AAA         1046
AA           521
Name: count, dtype: int64

In [28]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",3.0,Lithium BatteryWeight: 0.3 kgNA,1,"₹5,999",52% off,3 Ratings & 0 Reviews,EarShades,Lithium
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,"₹3,248",3.2,Lithium BatteryWeight: 410 gno,1,"₹12,999",75% off,487 Ratings & 24 Reviews,Super,Lithium
2,harshiv E88 Pro Drone 4k HD foldable With Came...,"₹1,749",1.8,Lithium BatteryWeight: 200 gNA,1,"₹4,999",65% off,6 Ratings & 1 Reviews,harshiv,Lithium
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...","₹1,649",3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,"₹2,899",43% off,83 Ratings & 4 Reviews,JOYBOX,AA
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,"₹2,599",2.8,Lithium BatteryWeight: 0.3 kgNA,1,"₹6,999",62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium
...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,"₹3,780",3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,"₹7,999",52% off,3 Ratings & 0 Reviews,VYZN,Lithium
12452,TodFod E88 with double Battery Drone,"₹1,910",3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,"₹3,999",52% off,3 Ratings & 0 Reviews,TodFod,AAA
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,"₹7,455",3.1,Lithium BatteryWeight: 1.14 kgna,538,"₹14,999",50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,"₹7,644",1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,"₹9,990",23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium
12455,Fourbrother Black Quadcopter Drone,"₹1,971",3.2,Lithium BatteryWeight: 320 gNA,538,"₹19,999",90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium

In [29]:
df.head(1)

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",3.0,Lithium BatteryWeight: 0.3 kgNA,1,"₹5,999",52% off,3 Ratings & 0 Reviews,EarShades,Lithium

In [30]:
df["Ratings1"] = df["Review"].apply (lambda x: re.split(r"[&]",x)[0])

In [31]:
df["no_of_Ratings"] = df["Ratings1"].apply(lambda x: re.findall(r"[\d,]+",x)[0].replace(",","")).astype("int")

In [32]:
df["Reviews1"] = df["Review"].apply (lambda x: re.split(r"[&]",x)[1])

In [33]:
df["no_of_Reviews"] = df["Reviews1"].apply (lambda x: re.findall(r"[\d,]+",x)[0].replace(",","")).astype("int")

In [34]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews
0,EarShades J2 Pro Foldable Drone with HD Camera...,"₹2,826",3.0,Lithium BatteryWeight: 0.3 kgNA,1,"₹5,999",52% off,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,"₹3,248",3.2,Lithium BatteryWeight: 410 gno,1,"₹12,999",75% off,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24
2,harshiv E88 Pro Drone 4k HD foldable With Came...,"₹1,749",1.8,Lithium BatteryWeight: 200 gNA,1,"₹4,999",65% off,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...","₹1,649",3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,"₹2,899",43% off,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,"₹2,599",2.8,Lithium BatteryWeight: 0.3 kgNA,1,"₹6,999",62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,"₹3,780",3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,"₹7,999",52% off,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0
12452,TodFod E88 with double Battery Drone,"₹1,910",3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,"₹3,999",52% off,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,"₹7,455",3.1,Lithium BatteryWeight: 1.14 kgna,538,"₹14,999",50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,"₹7,644",1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,"₹9,990",23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1
12455,Fourbrother Black Quadcopter Drone,"₹1,971",3.2,Lithium BatteryWeight: 320 gNA,538,"₹19,999",90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9

In [36]:
df["price"] = df["price"].apply(lambda x: re.sub(r"[₹,]","",x)).astype("int")

TypeError: expected string or bytes-like object, got 'float'

In [38]:
import re

df["price"] = (
    df["price"]
    .astype(str)                       # convert everything to string
    .str.replace(r"[₹,]", "", regex=True)  # remove ₹ and ,
    .astype(float)                     # handle empty/NaN safely
    .astype("Int64")                   # integer column (nullable)
)

In [39]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,"₹5,999",52% off,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,"₹12,999",75% off,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,"₹4,999",65% off,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,"₹2,899",43% off,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,"₹6,999",62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,"₹7,999",52% off,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,"₹3,999",52% off,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,"₹14,999",50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,"₹9,990",23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,"₹19,999",90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9

In [40]:
df.isnull().sum()

product_name       0
price             24
Rating             0
Features           0
pagenum            0
original_price    24
Discount          24
Review             0
Brand              0
processor          0
Ratings1           0
no_of_Ratings      0
Reviews1           0
no_of_Reviews      0
dtype: int64

In [41]:
df["original_price"].mode()[0]

'₹19,999'

In [42]:
df["original_price"].fillna(df["original_price"].mode()[0],inplace = True)

In [43]:
df.isnull().sum()

product_name       0
price             24
Rating             0
Features           0
pagenum            0
original_price     0
Discount          24
Review             0
Brand              0
processor          0
Ratings1           0
no_of_Ratings      0
Reviews1           0
no_of_Reviews      0
dtype: int64

In [44]:
df["Discount"].fillna(df["Discount"].mode()[0],inplace = True)

In [45]:
df.isnull().sum()

product_name       0
price             24
Rating             0
Features           0
pagenum            0
original_price     0
Discount           0
Review             0
Brand              0
processor          0
Ratings1           0
no_of_Ratings      0
Reviews1           0
no_of_Reviews      0
dtype: int64

In [46]:
df["original_price"].apply(lambda x: re.sub("[₹,]","",x)).astype("int")

0         5999
1        12999
2         4999
3         2899
4         6999
         ...
12451     7999
12452     3999
12453    14999
12454     9990
12455    19999
Name: original_price, Length: 12456, dtype: int64

In [47]:
df["original_price"] = df["original_price"].apply(lambda x: re.sub(r"[₹,]","",str(x))).astype(int)

In [48]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52% off,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75% off,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65% off,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43% off,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52% off,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52% off,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9

In [49]:
df.isna().sum()

product_name       0
price             24
Rating             0
Features           0
pagenum            0
original_price     0
Discount           0
Review             0
Brand              0
processor          0
Ratings1           0
no_of_Ratings      0
Reviews1           0
no_of_Reviews      0
dtype: int64

In [50]:
df.dropna(inplace = True)

In [51]:
df.isnull().sum()

product_name      0
price             0
Rating            0
Features          0
pagenum           0
original_price    0
Discount          0
Review            0
Brand             0
processor         0
Ratings1          0
no_of_Ratings     0
Reviews1          0
no_of_Reviews     0
dtype: int64

In [52]:
df["Features"][0]

'Lithium BatteryWeight: 0.3 kgNA'

In [53]:
df["battery_weight"] = df["Features"].apply(
    lambda x: re.search(r"BatteryWeight:\s*([\d.]+)", str(x)).group(1)
    if re.search(r"BatteryWeight:\s*([\d.]+)", str(x))
    else None
)

df["battery_weight"] = df["battery_weight"].astype(float)

In [54]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews,battery_weight
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52% off,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0,0.300
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75% off,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24,410.000
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65% off,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1,200.000
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43% off,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4,0.433
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2,0.300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52% off,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0,200.000
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52% off,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0,0.400
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0,1.140
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1,1.140
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9,320.000

In [55]:
df["warranty"] = df["Features"].str.extract(r"(NA)$")

In [56]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews,battery_weight,warranty
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52% off,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0,0.300,NA
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75% off,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24,410.000,NaN
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65% off,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1,200.000,NA
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43% off,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4,0.433,NaN
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2,0.300,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52% off,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0,200.000,NaN
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52% off,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0,0.400,NaN
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0,1.140,NaN
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1,1.140,NaN
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9,320.000,NA

In [57]:
df["warranty"] = df["warranty"].fillna("NO")

In [58]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews,battery_weight,warranty
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52% off,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0,0.300,NA
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75% off,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24,410.000,NO
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65% off,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1,200.000,NA
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43% off,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4,0.433,NO
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62% off,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2,0.300,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52% off,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0,200.000,NO
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52% off,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0,0.400,NO
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50% off,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0,1.140,NO
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23% off,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1,1.140,NO
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90% off,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9,320.000,NA

In [59]:
df["Discount"] = (
    df["Discount"]
    .str.extract(r"(\d+)")
    .astype(int)
)

In [60]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,Ratings1,no_of_Ratings,Reviews1,no_of_Reviews,battery_weight,warranty
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52,3 Ratings & 0 Reviews,EarShades,Lithium,3 Ratings,3,0 Reviews,0,0.300,NA
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75,487 Ratings & 24 Reviews,Super,Lithium,487 Ratings,487,24 Reviews,24,410.000,NO
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65,6 Ratings & 1 Reviews,harshiv,Lithium,6 Ratings,6,1 Reviews,1,200.000,NA
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43,83 Ratings & 4 Reviews,JOYBOX,AA,83 Ratings,83,4 Reviews,4,0.433,NO
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62,62 Ratings & 2 Reviews,NOWAIT,Lithium,62 Ratings,62,2 Reviews,2,0.300,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52,3 Ratings & 0 Reviews,VYZN,Lithium,3 Ratings,3,0 Reviews,0,200.000,NO
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52,3 Ratings & 0 Reviews,TodFod,AAA,3 Ratings,3,0 Reviews,0,0.400,NO
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50,30 Ratings & 0 Reviews,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,0,1.140,NO
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23,2 Ratings & 1 Reviews,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,1,1.140,NO
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90,318 Ratings & 9 Reviews,Fourbrother,Lithium,318 Ratings,318,9 Reviews,9,320.000,NA

In [61]:
df["product_name"][0]

'EarShades J2 Pro Foldable Drone with HD Camera,Altitude Hold, One-Key Takeoff/Landing E239 Drone'

In [ ]:
import pandas as pd
import numpy as np
import re

#  Brand (First word)
df["brand"] = df["product_name"].str.split().str[0]

#  Model (word after brand until 'Foldable' or 'Drone')
df["model"] = df["product_name"].str.extract(
    r"^[^\s]+\s+(.*?)(?=\sFoldable|\sDrone)"
)

# Product Type
df["product_type"] = df["product_name"].str.extract(r"(Drone)", expand=False)

# Foldable (Yes/No)
df["foldable"] = np.where(
    df["product_name"].str.contains("Foldable", case=False, na=False),
    "Yes",
    "No"
)

#  Camera Type
df["camera"] = df["product_name"].str.extract(r"(HD Camera)", expand=False)

# Altitude Hold (Yes/No)
df["altitude_hold"] = np.where(
    df["product_name"].str.contains("Altitude Hold", case=False, na=False),
    "Yes",
    "No"
)

# One-Key Takeoff/Landing (Yes/No)
df["one_key_takeoff"] = np.where(
    df["product_name"].str.contains("One-Key Takeoff/Landing", case=False, na=False),
    "Yes",
    "No"
)

In [63]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,...,no_of_Reviews,battery_weight,warranty,brand,model,product_type,foldable,camera,altitude_hold,one_key_takeoff
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52,3 Ratings & 0 Reviews,EarShades,Lithium,...,0,0.300,NA,EarShades,J2 Pro,Drone,Yes,HD Camera,Yes,Yes
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75,487 Ratings & 24 Reviews,Super,Lithium,...,24,410.000,NO,Super,Toy Brushless 4K Dual Camera,Drone,No,NaN,No,No
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65,6 Ratings & 1 Reviews,harshiv,Lithium,...,1,200.000,NA,harshiv,E88 Pro,Drone,Yes,NaN,No,No
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43,83 Ratings & 4 Reviews,JOYBOX,AA,...,4,0.433,NO,JOYBOX,Foldable,Drone,Yes,HD Camera,Yes,No
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62,62 Ratings & 2 Reviews,NOWAIT,Lithium,...,2,0.300,NA,NOWAIT,Advanced E88 4K Dual Camera,Drone,No,NaN,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52,3 Ratings & 0 Reviews,VYZN,Lithium,...,0,200.000,NO,VYZN,MAX-FLY,Drone,No,NaN,No,No
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52,3 Ratings & 0 Reviews,TodFod,AAA,...,0,0.400,NO,TodFod,E88 with double Battery,Drone,No,NaN,No,No
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50,30 Ratings & 0 Reviews,GAMESOUL,Lithium,...,0,1.140,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,Drone,No,NaN,No,No
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23,2 Ratings & 1 Reviews,GAMESOUL,Lithium,...,1,1.140,NO,GAMESOUL,A21 Pro Mini,Drone,Yes,NaN,No,No
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90,318 Ratings & 9 Reviews,Fourbrother,Lithium,...,9,320.000,NA,Fourbrother,Black Quadcopter,Drone,No,NaN,No,No

In [64]:
df.shape

(12432, 23)

In [65]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,...,no_of_Reviews,battery_weight,warranty,brand,model,product_type,foldable,camera,altitude_hold,one_key_takeoff
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52,3 Ratings & 0 Reviews,EarShades,Lithium,...,0,0.300,NA,EarShades,J2 Pro,Drone,Yes,HD Camera,Yes,Yes
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75,487 Ratings & 24 Reviews,Super,Lithium,...,24,410.000,NO,Super,Toy Brushless 4K Dual Camera,Drone,No,NaN,No,No
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65,6 Ratings & 1 Reviews,harshiv,Lithium,...,1,200.000,NA,harshiv,E88 Pro,Drone,Yes,NaN,No,No
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43,83 Ratings & 4 Reviews,JOYBOX,AA,...,4,0.433,NO,JOYBOX,Foldable,Drone,Yes,HD Camera,Yes,No
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62,62 Ratings & 2 Reviews,NOWAIT,Lithium,...,2,0.300,NA,NOWAIT,Advanced E88 4K Dual Camera,Drone,No,NaN,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52,3 Ratings & 0 Reviews,VYZN,Lithium,...,0,200.000,NO,VYZN,MAX-FLY,Drone,No,NaN,No,No
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52,3 Ratings & 0 Reviews,TodFod,AAA,...,0,0.400,NO,TodFod,E88 with double Battery,Drone,No,NaN,No,No
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50,30 Ratings & 0 Reviews,GAMESOUL,Lithium,...,0,1.140,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,Drone,No,NaN,No,No
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23,2 Ratings & 1 Reviews,GAMESOUL,Lithium,...,1,1.140,NO,GAMESOUL,A21 Pro Mini,Drone,Yes,NaN,No,No
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90,318 Ratings & 9 Reviews,Fourbrother,Lithium,...,9,320.000,NA,Fourbrother,Black Quadcopter,Drone,No,NaN,No,No

In [66]:
#df.columns

In [67]:
df[['no_of_ratings','no_of_reviews']] = df['Review'].str.replace(',', '').str.extract(r'(\d+).+?(\d+)').astype(int)

In [68]:
df

,product_name,price,Rating,Features,pagenum,original_price,Discount,Review,Brand,processor,...,warranty,brand,model,product_type,foldable,camera,altitude_hold,one_key_takeoff,no_of_ratings,no_of_reviews
0,EarShades J2 Pro Foldable Drone with HD Camera...,2826,3.0,Lithium BatteryWeight: 0.3 kgNA,1,5999,52,3 Ratings & 0 Reviews,EarShades,Lithium,...,NA,EarShades,J2 Pro,Drone,Yes,HD Camera,Yes,Yes,3,0
1,Super Toy Brushless 4K Dual Camera Drone 5-Sid...,3248,3.2,Lithium BatteryWeight: 410 gno,1,12999,75,487 Ratings & 24 Reviews,Super,Lithium,...,NO,Super,Toy Brushless 4K Dual Camera,Drone,No,NaN,No,No,487,24
2,harshiv E88 Pro Drone 4k HD foldable With Came...,1749,1.8,Lithium BatteryWeight: 200 gNA,1,4999,65,6 Ratings & 1 Reviews,harshiv,Lithium,...,NA,harshiv,E88 Pro,Drone,Yes,NaN,No,No,6,1
3,"JOYBOX Foldable Drone with Full HD Camera, WiF...",1649,3.2,AA Rechargeable BatteryWeight: 0.433 kgN/a,1,2899,43,83 Ratings & 4 Reviews,JOYBOX,AA,...,NO,JOYBOX,Foldable,Drone,Yes,HD Camera,Yes,No,83,4
4,NOWAIT Advanced E88 4K Dual Camera Drone with ...,2599,2.8,Lithium BatteryWeight: 0.3 kgNA,1,6999,62,62 Ratings & 2 Reviews,NOWAIT,Lithium,...,NA,NOWAIT,Advanced E88 4K Dual Camera,Drone,No,NaN,No,No,62,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,VYZN MAX-FLY Drone,3780,3.0,Lithium BatteryWeight: 200 g6 months warranty ...,538,7999,52,3 Ratings & 0 Reviews,VYZN,Lithium,...,NO,VYZN,MAX-FLY,Drone,No,NaN,No,No,3,0
12452,TodFod E88 with double Battery Drone,1910,3.0,AAA Rechargeable BatteryWeight: 0.4 kgDomestic...,538,3999,52,3 Ratings & 0 Reviews,TodFod,AAA,...,NO,TodFod,E88 with double Battery,Drone,No,NaN,No,No,3,0
12453,GAMESOUL JS39P 4K Brushless Motor With Gimbal ...,7455,3.1,Lithium BatteryWeight: 1.14 kgna,538,14999,50,30 Ratings & 0 Reviews,GAMESOUL,Lithium,...,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,Drone,No,NaN,No,No,30,0
12454,GAMESOUL A21 Pro Mini Drone With Wifi Helicopt...,7644,1.0,Lithium BatteryWeight: 1.14 kg1 Month Seller W...,538,9990,23,2 Ratings & 1 Reviews,GAMESOUL,Lithium,...,NO,GAMESOUL,A21 Pro Mini,Drone,Yes,NaN,No,No,2,1
12455,Fourbrother Black Quadcopter Drone,1971,3.2,Lithium BatteryWeight: 320 gNA,538,19999,90,318 Ratings & 9 Reviews,Fourbrother,Lithium,...,NA,Fourbrother,Black Quadcopter,Drone,No,NaN,No,No,318,9

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12432 entries, 0 to 12455
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_name     12432 non-null  object
 1   price            12432 non-null  Int64
 2   Rating           12432 non-null  float64
 3   Features         12432 non-null  object
 4   pagenum          12432 non-null  int64
 5   original_price   12432 non-null  int64
 6   Discount         12432 non-null  int64
 7   Review           12432 non-null  object
 8   Brand            12432 non-null  object
 9   processor        12432 non-null  object
 10  Ratings1         12432 non-null  object
 11  no_of_Ratings    12432 non-null  int64
 12  Reviews1         12432 non-null  object
 13  no_of_Reviews    12432 non-null  int64
 14  battery_weight   12432 non-null  float64
 15  warranty         12432 non-null  object
 16  brand            12432 non-null  object
 17  model            12432 non-null  object
 18  product_type     12432 non-null  object
 19  foldable         12432 non-null  object
 20  camera           1286 non-null   object
 21  altitude_hold    12432 non-null  object
 22  one_key_takeoff  12432 non-null  object
 23  no_of_ratings    12432 non-null  int64
 24  no_of_reviews    12432 non-null  int64
dtypes: Int64(1), float64(2), int64(7), object(15)
memory usage: 2.7+ MB

In [70]:
df.drop(columns=['product_name', 'Features', 'Review','product_type'],inplace = True)

In [71]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,Ratings1,no_of_Ratings,Reviews1,...,battery_weight,warranty,brand,model,foldable,camera,altitude_hold,one_key_takeoff,no_of_ratings,no_of_reviews
0,2826,3.0,1,5999,52,EarShades,Lithium,3 Ratings,3,0 Reviews,...,0.300,NA,EarShades,J2 Pro,Yes,HD Camera,Yes,Yes,3,0
1,3248,3.2,1,12999,75,Super,Lithium,487 Ratings,487,24 Reviews,...,410.000,NO,Super,Toy Brushless 4K Dual Camera,No,NaN,No,No,487,24
2,1749,1.8,1,4999,65,harshiv,Lithium,6 Ratings,6,1 Reviews,...,200.000,NA,harshiv,E88 Pro,Yes,NaN,No,No,6,1
3,1649,3.2,1,2899,43,JOYBOX,AA,83 Ratings,83,4 Reviews,...,0.433,NO,JOYBOX,Foldable,Yes,HD Camera,Yes,No,83,4
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62 Ratings,62,2 Reviews,...,0.300,NA,NOWAIT,Advanced E88 4K Dual Camera,No,NaN,No,No,62,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,3780,3.0,538,7999,52,VYZN,Lithium,3 Ratings,3,0 Reviews,...,200.000,NO,VYZN,MAX-FLY,No,NaN,No,No,3,0
12452,1910,3.0,538,3999,52,TodFod,AAA,3 Ratings,3,0 Reviews,...,0.400,NO,TodFod,E88 with double Battery,No,NaN,No,No,3,0
12453,7455,3.1,538,14999,50,GAMESOUL,Lithium,30 Ratings,30,0 Reviews,...,1.140,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,No,NaN,No,No,30,0
12454,7644,1.0,538,9990,23,GAMESOUL,Lithium,2 Ratings,2,1 Reviews,...,1.140,NO,GAMESOUL,A21 Pro Mini,Yes,NaN,No,No,2,1
12455,1971,3.2,538,19999,90,Fourbrother,Lithium,318 Ratings,318,9 Reviews,...,320.000,NA,Fourbrother,Black Quadcopter,No,NaN,No,No,318,9

In [72]:
df.drop(columns=['Ratings1', 'Reviews1'],inplace = True)

In [73]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,warranty,brand,model,foldable,camera,altitude_hold,one_key_takeoff,no_of_ratings,no_of_reviews
0,2826,3.0,1,5999,52,EarShades,Lithium,3,0,0.300,NA,EarShades,J2 Pro,Yes,HD Camera,Yes,Yes,3,0
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.000,NO,Super,Toy Brushless 4K Dual Camera,No,NaN,No,No,487,24
2,1749,1.8,1,4999,65,harshiv,Lithium,6,1,200.000,NA,harshiv,E88 Pro,Yes,NaN,No,No,6,1
3,1649,3.2,1,2899,43,JOYBOX,AA,83,4,0.433,NO,JOYBOX,Foldable,Yes,HD Camera,Yes,No,83,4
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.300,NA,NOWAIT,Advanced E88 4K Dual Camera,No,NaN,No,No,62,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,3780,3.0,538,7999,52,VYZN,Lithium,3,0,200.000,NO,VYZN,MAX-FLY,No,NaN,No,No,3,0
12452,1910,3.0,538,3999,52,TodFod,AAA,3,0,0.400,NO,TodFod,E88 with double Battery,No,NaN,No,No,3,0
12453,7455,3.1,538,14999,50,GAMESOUL,Lithium,30,0,1.140,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,No,NaN,No,No,30,0
12454,7644,1.0,538,9990,23,GAMESOUL,Lithium,2,1,1.140,NO,GAMESOUL,A21 Pro Mini,Yes,NaN,No,No,2,1
12455,1971,3.2,538,19999,90,Fourbrother,Lithium,318,9,320.000,NA,Fourbrother,Black Quadcopter,No,NaN,No,No,318,9

In [74]:
df.drop(columns=['no_of_ratings', 'no_of_reviews'],inplace = True)

In [75]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,warranty,brand,model,foldable,camera,altitude_hold,one_key_takeoff
0,2826,3.0,1,5999,52,EarShades,Lithium,3,0,0.300,NA,EarShades,J2 Pro,Yes,HD Camera,Yes,Yes
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.000,NO,Super,Toy Brushless 4K Dual Camera,No,NaN,No,No
2,1749,1.8,1,4999,65,harshiv,Lithium,6,1,200.000,NA,harshiv,E88 Pro,Yes,NaN,No,No
3,1649,3.2,1,2899,43,JOYBOX,AA,83,4,0.433,NO,JOYBOX,Foldable,Yes,HD Camera,Yes,No
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.300,NA,NOWAIT,Advanced E88 4K Dual Camera,No,NaN,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,3780,3.0,538,7999,52,VYZN,Lithium,3,0,200.000,NO,VYZN,MAX-FLY,No,NaN,No,No
12452,1910,3.0,538,3999,52,TodFod,AAA,3,0,0.400,NO,TodFod,E88 with double Battery,No,NaN,No,No
12453,7455,3.1,538,14999,50,GAMESOUL,Lithium,30,0,1.140,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,No,NaN,No,No
12454,7644,1.0,538,9990,23,GAMESOUL,Lithium,2,1,1.140,NO,GAMESOUL,A21 Pro Mini,Yes,NaN,No,No
12455,1971,3.2,538,19999,90,Fourbrother,Lithium,318,9,320.000,NA,Fourbrother,Black Quadcopter,No,NaN,No,No

In [76]:
df.shape

(12432, 17)

In [77]:
df.isnull().sum()

price                  0
Rating                 0
pagenum                0
original_price         0
Discount               0
Brand                  0
processor              0
no_of_Ratings          0
no_of_Reviews          0
battery_weight         0
warranty               0
brand                  0
model                  0
foldable               0
camera             11146
altitude_hold          0
one_key_takeoff        0
dtype: int64

In [78]:
df["camera"].fillna(df["camera"].mode()[0],inplace = True)

In [79]:
df.isnull().sum()

price              0
Rating             0
pagenum            0
original_price     0
Discount           0
Brand              0
processor          0
no_of_Ratings      0
no_of_Reviews      0
battery_weight     0
warranty           0
brand              0
model              0
foldable           0
camera             0
altitude_hold      0
one_key_takeoff    0
dtype: int64

In [80]:
df.duplicated().sum()

np.int64(9)

In [81]:
df.drop_duplicates(inplace=True)

In [82]:
df.duplicated().sum()

np.int64(0)

In [83]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,warranty,brand,model,foldable,camera,altitude_hold,one_key_takeoff
0,2826,3.0,1,5999,52,EarShades,Lithium,3,0,0.300,NA,EarShades,J2 Pro,Yes,HD Camera,Yes,Yes
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.000,NO,Super,Toy Brushless 4K Dual Camera,No,HD Camera,No,No
2,1749,1.8,1,4999,65,harshiv,Lithium,6,1,200.000,NA,harshiv,E88 Pro,Yes,HD Camera,No,No
3,1649,3.2,1,2899,43,JOYBOX,AA,83,4,0.433,NO,JOYBOX,Foldable,Yes,HD Camera,Yes,No
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.300,NA,NOWAIT,Advanced E88 4K Dual Camera,No,HD Camera,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,3780,3.0,538,7999,52,VYZN,Lithium,3,0,200.000,NO,VYZN,MAX-FLY,No,HD Camera,No,No
12452,1910,3.0,538,3999,52,TodFod,AAA,3,0,0.400,NO,TodFod,E88 with double Battery,No,HD Camera,No,No
12453,7455,3.1,538,14999,50,GAMESOUL,Lithium,30,0,1.140,NO,GAMESOUL,JS39P 4K Brushless Motor With Gimbal Camera,No,HD Camera,No,No
12454,7644,1.0,538,9990,23,GAMESOUL,Lithium,2,1,1.140,NO,GAMESOUL,A21 Pro Mini,Yes,HD Camera,No,No
12455,1971,3.2,538,19999,90,Fourbrother,Lithium,318,9,320.000,NA,Fourbrother,Black Quadcopter,No,HD Camera,No,No

In [84]:
df.drop(columns=['brand' ],inplace = True)

In [85]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,warranty,model,foldable,camera,altitude_hold,one_key_takeoff
0,2826,3.0,1,5999,52,EarShades,Lithium,3,0,0.300,NA,J2 Pro,Yes,HD Camera,Yes,Yes
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.000,NO,Toy Brushless 4K Dual Camera,No,HD Camera,No,No
2,1749,1.8,1,4999,65,harshiv,Lithium,6,1,200.000,NA,E88 Pro,Yes,HD Camera,No,No
3,1649,3.2,1,2899,43,JOYBOX,AA,83,4,0.433,NO,Foldable,Yes,HD Camera,Yes,No
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.300,NA,Advanced E88 4K Dual Camera,No,HD Camera,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12451,3780,3.0,538,7999,52,VYZN,Lithium,3,0,200.000,NO,MAX-FLY,No,HD Camera,No,No
12452,1910,3.0,538,3999,52,TodFod,AAA,3,0,0.400,NO,E88 with double Battery,No,HD Camera,No,No
12453,7455,3.1,538,14999,50,GAMESOUL,Lithium,30,0,1.140,NO,JS39P 4K Brushless Motor With Gimbal Camera,No,HD Camera,No,No
12454,7644,1.0,538,9990,23,GAMESOUL,Lithium,2,1,1.140,NO,A21 Pro Mini,Yes,HD Camera,No,No
12455,1971,3.2,538,19999,90,Fourbrother,Lithium,318,9,320.000,NA,Black Quadcopter,No,HD Camera,No,No

In [86]:
df.to_csv("cleaned2_drones_new.csv",index = False)

In [87]:
import os
os.getcwd()

'C:\\Users\\Sandeep'

In [88]:
df = pd.read_csv("cleaned2_drones_new.csv")

In [89]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,warranty,model,foldable,camera,altitude_hold,one_key_takeoff
0,2826,3.0,1,5999,52,EarShades,Lithium,3,0,0.300,NaN,J2 Pro,Yes,HD Camera,Yes,Yes
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.000,NO,Toy Brushless 4K Dual Camera,No,HD Camera,No,No
2,1749,1.8,1,4999,65,harshiv,Lithium,6,1,200.000,NaN,E88 Pro,Yes,HD Camera,No,No
3,1649,3.2,1,2899,43,JOYBOX,AA,83,4,0.433,NO,Foldable,Yes,HD Camera,Yes,No
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.300,NaN,Advanced E88 4K Dual Camera,No,HD Camera,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12418,3780,3.0,538,7999,52,VYZN,Lithium,3,0,200.000,NO,MAX-FLY,No,HD Camera,No,No
12419,1910,3.0,538,3999,52,TodFod,AAA,3,0,0.400,NO,E88 with double Battery,No,HD Camera,No,No
12420,7455,3.1,538,14999,50,GAMESOUL,Lithium,30,0,1.140,NO,JS39P 4K Brushless Motor With Gimbal Camera,No,HD Camera,No,No
12421,7644,1.0,538,9990,23,GAMESOUL,Lithium,2,1,1.140,NO,A21 Pro Mini,Yes,HD Camera,No,No
12422,1971,3.2,538,19999,90,Fourbrother,Lithium,318,9,320.000,NaN,Black Quadcopter,No,HD Camera,No,No

In [90]:
df.isnull().sum()

price                 0
Rating                0
pagenum               0
original_price        0
Discount              0
Brand                 0
processor             0
no_of_Ratings         0
no_of_Reviews         0
battery_weight        0
warranty           5653
model                 0
foldable              0
camera                0
altitude_hold         0
one_key_takeoff       0
dtype: int64

In [92]:
df.drop(columns=['warranty'],inplace = True)

In [93]:
df

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,model,foldable,camera,altitude_hold,one_key_takeoff
0,2826,3.0,1,5999,52,EarShades,Lithium,3,0,0.300,J2 Pro,Yes,HD Camera,Yes,Yes
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.000,Toy Brushless 4K Dual Camera,No,HD Camera,No,No
2,1749,1.8,1,4999,65,harshiv,Lithium,6,1,200.000,E88 Pro,Yes,HD Camera,No,No
3,1649,3.2,1,2899,43,JOYBOX,AA,83,4,0.433,Foldable,Yes,HD Camera,Yes,No
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.300,Advanced E88 4K Dual Camera,No,HD Camera,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12418,3780,3.0,538,7999,52,VYZN,Lithium,3,0,200.000,MAX-FLY,No,HD Camera,No,No
12419,1910,3.0,538,3999,52,TodFod,AAA,3,0,0.400,E88 with double Battery,No,HD Camera,No,No
12420,7455,3.1,538,14999,50,GAMESOUL,Lithium,30,0,1.140,JS39P 4K Brushless Motor With Gimbal Camera,No,HD Camera,No,No
12421,7644,1.0,538,9990,23,GAMESOUL,Lithium,2,1,1.140,A21 Pro Mini,Yes,HD Camera,No,No
12422,1971,3.2,538,19999,90,Fourbrother,Lithium,318,9,320.000,Black Quadcopter,No,HD Camera,No,No

In [94]:
df.isnull().sum()

price              0
Rating             0
pagenum            0
original_price     0
Discount           0
Brand              0
processor          0
no_of_Ratings      0
no_of_Reviews      0
battery_weight     0
model              0
foldable           0
camera             0
altitude_hold      0
one_key_takeoff    0
dtype: int64

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df.to_csv("cleaned3_drones_new.csv",index = False)

In [101]:
df["Brand"].value_counts()

Brand
Super            2313
DRONE             789
Rostystar         765
NOWAIT            762
Antman            758
BYGO              523
DIYAN             523
MAYURI            518
Zyamalox          518
RBR               518
Clubmall          518
Toyterra          515
JOYBOX            515
harshiv           515
EarShades         510
GAMESOUL          281
TodFod            273
VYZN              273
Orivox            261
CRISANTOWILLA     253
IRINWE            247
WALLINSTIK        247
Fourbrother        13
Divine              6
Acqua               3
zone                3
widria              3
Name: count, dtype: int64

In [102]:
top10_brands = df["Brand"].value_counts().head(10).index

# keep only rows belonging to those brands
# df_top10 = df[df["Brand"].isin(top10_brands)].copy()

In [103]:
df_top10 = df[df["Brand"].isin(top10_brands)].copy()

In [106]:
df_top10

,price,Rating,pagenum,original_price,Discount,Brand,processor,no_of_Ratings,no_of_Reviews,battery_weight,model,foldable,camera,altitude_hold,one_key_takeoff
1,3248,3.2,1,12999,75,Super,Lithium,487,24,410.0,Toy Brushless 4K Dual Camera,No,HD Camera,No,No
4,2599,2.8,1,6999,62,NOWAIT,Lithium,62,2,0.3,Advanced E88 4K Dual Camera,No,HD Camera,No,No
5,7369,2.8,1,19999,63,Super,Lithium,56,1,250.0,Toy 4K Dual Camera,No,HD Camera,No,No
7,1499,3.3,1,2999,50,DRONE,AAA,3,0,650.0,E88,No,HD Camera,No,No
9,1788,3.0,1,4499,60,Rostystar,Lithium,3,0,200.0,Drone With Camera E88 Toy Flodable,No,HD Camera,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12412,1745,3.0,538,8943,80,NOWAIT,Lithium,4,1,0.3,E88 HD 4K,No,HD Camera,No,No
12413,1814,2.8,538,4999,63,Zyamalox,Lithium,1473,39,0.2,"ZX drone with camera 4k ,12 MP ,fly 30 minutes",No,HD Camera,No,No
12414,2049,3.0,538,6999,70,MAYURI,Lithium,184,5,150.0,CREATIONS Black Quadcopter,No,HD Camera,No,No
12415,3396,3.0,538,9999,66,DRONE,Lithium,3,0,100.0,Dual Camera With Smart Lighting,No,HD Camera,No,No
12417,9248,3.0,538,19999,53,Super,Lithium,3,0,240.0,Toy 4K Dual Camera RC,No,HD Camera,No,No

In [105]:
df["Brand"].value_counts()

Brand
Super            2313
DRONE             789
Rostystar         765
NOWAIT            762
Antman            758
BYGO              523
DIYAN             523
MAYURI            518
Zyamalox          518
RBR               518
Clubmall          518
Toyterra          515
JOYBOX            515
harshiv           515
EarShades         510
GAMESOUL          281
TodFod            273
VYZN              273
Orivox            261
CRISANTOWILLA     253
IRINWE            247
WALLINSTIK        247
Fourbrother        13
Divine              6
Acqua               3
zone                3
widria              3
Name: count, dtype: int64

In [109]:
df_top10.to_excel("top10_drones.xlsx", index=False)